"""Update previous_price with default value

Revision ID: 47eaf042d479
Revises: 4c7b51442979
Create Date: 2023-03-21 07:03:32.189606

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '47eaf042d479'
down_revision = '4c7b51442979'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('stock', schema=None) as batch_op:
        batch_op.add_column(sa.Column('prev_price', sa.Float(), nullable=True))
        batch_op.drop_column('previous_price')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('stock', schema=None) as batch_op:
        batch_op.add_column(sa.Column('previous_price', sa.FLOAT(), nullable=True))
        batch_op.drop_column('prev_price')

    # ### end Alembic commands ###
