"""Update high and low to stock

Revision ID: 58454641bbc0
Revises: 47eaf042d479
Create Date: 2023-03-21 07:52:27.989399

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '58454641bbc0'
down_revision = '47eaf042d479'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('stock', schema=None) as batch_op:
        batch_op.add_column(sa.Column('high', sa.Float(), nullable=True))
        batch_op.add_column(sa.Column('low', sa.Float(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('stock', schema=None) as batch_op:
        batch_op.drop_column('low')
        batch_op.drop_column('high')

    # ### end Alembic commands ###
